services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: eventflow_app
    working_dir: /var/www/api
    volumes:
      - ./api:/var/www/api
    environment:
      APP_ENV: dev
      DATABASE_URL: "mysql://root:@host.docker.internal:3306/eventflow?serverVersion=10.4.32-MariaDB&charset=utf8mb4"


  nginx:
    image: nginx:alpine
    container_name: eventflow_nginx
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www/api
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app